### ISSUE TITLE
ERROR: Could not build wheels for SharedArray, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by SE-Nickjackson** [rayguan97/M3DETR#8]
When I install SharedArray, it give me error below:
------------------------------
Building wheels for collected packages: SharedArray
  Building wheel for SharedArray (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'F:\OutSourcing\3d_object_detection\M3DETR\venv\Scripts\python.exe' 'F:\OutSourcing\3d_object_detection\M3DETR\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\CAIFEN~1\AppData\Local\Temp\tmpnoay6_36'      
       cwd: C:\Users\Cai Feng Lin\AppData\Local\Temp\pip-install-gc0uej1o\sharedarray_a6aff881d25c4fab845553e526ed24db
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'SharedArray' extension
  creating build
  creating build\temp.win-amd64-cpython-38
  creating build\temp.win-amd64-cpython-38\Release
  creating build\temp.win-amd64-cpython-38\Release\src
  D:\Tools\VisualStudio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-I
C:\Users\Cai Feng Lin\AppData\Local\Temp\pip-build-env-cqhwb4q3\overlay\Lib\site-packages\numpy\core\include" -IF:\OutSourcing\3d_
object_detection\M3DETR\venv\include -ID:\Tools\Python\Python38\include -ID:\Tools\Python\Python38\Include -ID:\Tools\VisualStudio
\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\include -ID:\Tools\VisualStudio\2019\Professional\VC\Tools\MSVC\14.29.30133\in
clude "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-ID:\Windows Kits\10\include\10.0.19041.0\ucrt" "-ID:\Windo
ws Kits\10\include\10.0.19041.0\shared" "-ID:\Windows Kits\10\include\10.0.19041.0\um" "-ID:\Windows Kits\10\include\10.0.19041.0\
winrt" "-ID:\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tc.\src\map_owner.c /Fobuild\temp.win-amd64-cpython-38\Release\.\src\map_owner.obj
  map_owner.c
  .\src\map_owner.c(19): fatal error C1083: Cannot open include file: 'sys/mman.h': No such file or directory
  error: command 'D:\\Tools\\VisualStudio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ERROR: Failed building wheel for SharedArray
Failed to build SharedArray
ERROR: Could not build wheels for SharedArray, which is required to install pyproject.toml-based projects
----------------------------------------
So, how can I solve it?

**Comment by HenryJunW** [comment]
Hello, could you try using 'pip install SharedArray' to install SharedArray?
